name: Build Kivy Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip git python3-pip openjdk-17-jdk libffi-dev libssl-dev libnss3 libc6 libncurses-dev build-essential

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer Cython

      - name: Clean corrupted spec file if exists
        run: |
          if grep -q 'wq' buildozer.spec 2>/dev/null; then
            rm buildozer.spec
          fi

      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: fitapp-apk
          path: bin/*.apk
