name: Build Kivy Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Accept Android SDK Licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Clean corrupted spec file if exists
        run: |
          if grep -q '^wq' buildozer.spec; then
            echo "Invalid buildozer.spec file detected. Replacing..."
            echo "[app]" > buildozer.spec
            echo "title = FitApp" >> buildozer.spec
            echo "package.name = fitapp" >> buildozer.spec
            echo "package.domain = org.nrvnitish" >> buildozer.spec
            echo "source.dir = ." >> buildozer.spec
            echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
            echo "version = 0.1" >> buildozer.spec
            echo "requirements = python3,kivy,kivymd" >> buildozer.spec
            echo "orientation = portrait" >> buildozer.spec
          fi

      - name: Initialize Buildozer
        run: buildozer init || true

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FitApp-APK
          path: bin/*.apk
