name: Build Kivy Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip unzip zip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Setup Android SDK & Accept Licenses
        env:
          ANDROID_HOME: ${{ runner.tool_cache }}/android/sdk
        run: |
          yes | sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0" "build-tools;36.0.0" "cmdline-tools;latest"
          yes | sdkmanager --licenses

      - name: Initialize Buildozer
        run: |
          buildozer init || true

      - name: Build APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FitApp-APK
          path: bin/*.apk
